### ISSUE TITLE
Docs 1.0.0

### ISSUE THREAD

**Issue by ss-o** [z-shell/zw#249]
## Todo

Docusaurus:

- [ ] https://github.com/rdilweb/docusaurus-plugin-remote-content

### tj/n

- [ ] Description for annex any-node
- [x] Check other plugin/annex if related.

```zsh
zi light-mode for as'program' atinit'export N_PREFIX="$HOME/n"; \
[[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"' pick"bin/n" \
    tj/n
```

### pnpm/pnpm

- [x] Add to collection/programs

```zsh
zi light-mode for from'gh-r' as'program' \
  atinit'export PNPM_HOME="$PWD"; export PATH="$PNPM_HOME:$PATH"' \
  mv'pnpm* -> pnpm' bpick'*-linux-x64' \
    pnpm/pnpm
```
